import { useState, useSyncExternalStore } from 'react';
import { accounts } from './accounts';
import { getDeviceSettings, saveDeviceSettings, subscribeSettings } from './settings-store';
import { decodeNerds, encodeNerds, MAX_SETTINGS_BYTES, settingsChanges, type NerdsFile, type Resolutions } from '../shared/settings';
import { themes } from './themes';
import './settings.css';
import { FavoriteSettings, carLabel } from './Favorites';
import { validFleetCarID } from '../shared/settings';
const labels:Record<string,string>={favorites:'Favorites',theme:'Theme',stations:'Stations',widgets:'Widgets',display:'Display',lockScreen:'Lock Screen',directionOrder:'Direction order',showService:'Service icons',fields:'Shown information',compact:'Compact rows',trainsPerDirection:'Trains per direction',timeStyle:'Arrival display',matchAppFilters:'Match app filters',direction:'Direction',routes:'Lines',view:'Board grouping',stationName:'Station name',carType:'Car types',carCount:'Car counts',carNumbers:'Car numbers',updatedAt:'Report time',refreshButton:'Refresh button',groupHeaders:'Grouping labels'};
Object.assign(labels, { favorites:'Favorite stations',trainFavorites:'Favorite trains',cars:'Cars',consists:'Consists',match:'Consist matching',stationSelection:'Station selection',mode:'Mode',radiusFeet:'Radius (ft)',followApp:'Follow app',selection:'Station choice',exact:'Exact consist',anyCar:'Any member car',favorite:'Closest favorite',closest:'Closest station',nearbyFavorite:'Favorite within radius' });
const human=(value:string)=>validFleetCarID(value)?carLabel(value):themes.find(t=>t.id===value)?.name||labels[value]||value.replaceAll('_',' ').replace(/^[a-z]/,c=>c.toUpperCase());
const show=(value:unknown):string=>value===undefined?'Not set':typeof value==='boolean'?value?'On':'Off':Array.isArray(value)?value.length?value.map(v=>Array.isArray(v)?`${v.length}-car consist: ${v.map(id=>human(String(id))).join(', ')}`:human(String(v))).join('; '):'None':value&&typeof value==='object'?Object.entries(value).map(([k,v])=>human(k)+': '+show(v)).join(' · '):human(String(value));
export default function SettingsPanel({stationNames,onTheme,onFleet}:{stationNames:Record<string,string>;onTheme:()=>void;onFleet:(id:string)=>void}){
	const device=useSyncExternalStore(subscribeSettings,getDeviceSettings);
	const account=useSyncExternalStore(accounts.subscribe,accounts.get);
	const [file,setFile]=useState<NerdsFile>();const[error,setError]=useState('');const[notice,setNotice]=useState('');
	const[choices,setChoices]=useState<Resolutions>({});const[deleting,setDeleting]=useState(false);const[unlink,setUnlink]=useState<string>();
	const label=(path:string)=>path.split(/\s\/\s|\//).filter(Boolean).map(p=>{const key=p.replaceAll('~1','/').replaceAll('~0','~');return stationNames[key]||human(key);}).join(' · ');
	const exportFile=()=>{try{
		const blob=new Blob([encodeNerds(device.settings,device.lastStation)],{type:'application/vnd.subwaysfornerds.settings+json'});
		const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='subway-settings-'+new Date().toISOString().slice(0,10)+'.nerds';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setError('');
	}catch(e){setError((e as Error).message);}};
	const importFile=async(selected:File)=>{setNotice('');setError('');setFile(undefined);try{if(selected.size>MAX_SETTINGS_BYTES)throw new Error('Settings files must be smaller than 1 MiB.');setFile(decodeNerds(await selected.text()));}catch(e){setError((e as Error).message);}};
	const confirmImport=()=>{if(!file)return;try{saveDeviceSettings({...getDeviceSettings(),settings:file.settings,lastStation:file.lastStation});setFile(undefined);setNotice('Settings imported.');}catch(e){setError((e as Error).message);}};
	return <div className="settings-panel">
		<section><h3>Your settings</h3><button className="text-button" onClick={onTheme}>Choose theme</button><div className="settings-actions"><button className="text-button" onClick={exportFile}>Export settings</button><label className="text-button settings-upload">Import settings<input type="file" accept=".nerds" aria-label="Import settings file" onChange={e=>{const selected=e.target.files?.[0];e.target.value='';if(selected)void importFile(selected);}} /></label></div><p className="fine-print">Move favorite stations and trains, station selection, themes, filters, and widget preferences between devices with a .nerds file. Files work without an account.</p></section>
		{file&&<section aria-label="Import preview"><h3>Replace settings?</h3><p>{file.settings.favorites.length} favorite stations · {file.settings.trainFavorites.cars.length} cars · {file.settings.trainFavorites.consists.length} consists · {show(file.settings.theme)} · Last station: {stationNames[file.lastStation]||file.lastStation}</p><dl className="settings-diff">{settingsChanges(device.settings,file.settings).map(change=><div key={change.path}><dt>{label(change.path)}</dt><dd><span>Current: {show(change.local)}</span><span>Imported: {show(change.remote)}</span></dd></div>)}</dl><p>{account.account?'This replaces settings on this device and will sync to your account.':'This replaces settings on this device.'}</p><div className="settings-actions"><button className="text-button" onClick={confirmImport}>Replace settings</button><button className="text-button" onClick={()=>setFile(undefined)}>Cancel import</button></div></section>}
		{(error||device.error)&&<p role="alert" className="notice">{error||device.error}</p>}{notice&&<p role="status">{notice}</p>}
		<FavoriteSettings openFleet={onFleet} />
		<section><h3>Account and sync</h3>
			{!account.ready?<p>Checking account availability…</p>:!account.enabled?<p>Sign-in is currently unavailable. You can still move settings with a .nerds file.</p>:!account.account?<><p>Sign in to keep your settings across devices. You can also keep using the app without an account.</p><div className="settings-actions"><button className="provider-button apple" onClick={()=>void accounts.login('apple')}>Continue with Apple</button><button className="provider-button google" onClick={()=>void accounts.login('google')}><img src={import.meta.env.BASE_URL+'google-sign-in.png'} width={20} height={20} alt="" />Continue with Google</button></div></>:<>
				<p role="status">{account.status}</p>
				{account.account.identities.map(identity=><div className="settings-identity" key={identity.provider}><span>{human(identity.provider)} · {identity.email||'Connected'}</span>{account.account!.identities.length>1&&<button className="text-button" onClick={()=>setUnlink(identity.provider)}>Unlink {human(identity.provider)}</button>}</div>)}
				{(['apple','google'] as const).filter(p=>!account.account!.identities.some(i=>i.provider===p)).map(provider=><button className="text-button" key={provider} onClick={()=>void accounts.login(provider,'link')}>Link {human(provider)}</button>)}
				{account.first?.settings&&<div><h4>Choose settings to start syncing</h4><p>This device and your account have different settings.</p><dl className="settings-diff">{settingsChanges(device.settings,account.first.settings).map(change=><div key={change.path}><dt>{label(change.path)}</dt><dd><span>This device: {show(change.local)}</span><span>Account: {show(change.remote)}</span></dd></div>)}</dl><div className="settings-actions"><button className="text-button" onClick={()=>void accounts.chooseInitial('local')}>Use this device’s settings</button><button className="text-button" onClick={()=>void accounts.chooseInitial('remote')}>Use account settings</button></div></div>}
				{account.conflicts&&<div><h4>Choose which changes to keep</h4>{account.conflicts.map(conflict=><label className="settings-conflict" key={conflict.path}>{label(conflict.path)}<select value={choices[conflict.path]||''} onChange={e=>setChoices({...choices,[conflict.path]:e.target.value as 'local'|'remote'})}><option value="" disabled>Choose a value</option><option value="local">This device: {show(conflict.local)}</option><option value="remote">Account: {show(conflict.remote)}</option></select></label>)}<button className="text-button" disabled={account.conflicts.some(c=>!choices[c.path])} onClick={()=>void accounts.resolve(choices)}>Save choices</button></div>}
				<div className="settings-actions"><button className="text-button" onClick={()=>void accounts.sync()}>Sync now</button><button className="text-button" onClick={()=>void accounts.logout()}>Sign out</button><button className="text-button danger" onClick={()=>setDeleting(true)}>Delete account</button></div>
				{(deleting||unlink)&&<div className="notice"><p>{deleting?'Delete your account and all synced settings? Settings already on devices will remain there.':'Unlink '+human(unlink!)+'? You will be signed out on all devices. Sign in with your remaining login method.'}</p><button className="text-button danger" onClick={()=>{void accounts.remove(deleting?undefined:unlink);setDeleting(false);setUnlink(undefined);}}>Confirm {deleting?'deletion':'unlink'}</button><button className="text-button" onClick={()=>{setDeleting(false);setUnlink(undefined);}}>Cancel</button></div>}
			</>}
			{account.error&&<div role="alert" className="notice">{account.error}{account.account&&<div className="settings-actions">{account.account.identities.map(i=><button key={i.provider} className="text-button" onClick={()=>void accounts.login(i.provider,'reauth')}>Verify again with {human(i.provider)}</button>)}</div>}</div>}
			<p className="fine-print">Your current station stays separate on each device. Signing out keeps local settings. <a href={import.meta.env.BASE_URL+'privacy.html'} target="_blank" rel="noreferrer">Privacy</a></p>
		</section>
	</div>;
}
